-- Postgres baseline: the same logical schema as migrations/*.sql (the SQLite/D1
-- source of truth), squashed. There are no Postgres deployments older than this
-- file, so there is no history worth replaying — and 0007's DROP/INSERT/RENAME
-- table rebuild exists only because SQLite cannot alter a CHECK constraint.
--
-- From here on a schema change ships in BOTH sets in the same PR, and
-- tests/schema-parity.test.ts compares the two live schemas so a one-sided edit
-- fails CI rather than surfacing as a driver-specific bug.

-- Timestamps are TEXT holding SQLite's `YYYY-MM-DD HH:MM:SS`, and that exact
-- shape is load-bearing: the status endpoint folds the space to a T for its ETag,
-- ordering relies on the format being fixed-width and lexicographic, and the
-- panel renders the string as-is. So rather than rewrite 20 call sites' SQL (or
-- migrate the columns to timestamptz and change all three), Postgres gets the
-- function they already call. Only `datetime('now')` is implemented — anything
-- else raises instead of quietly returning the wrong instant.
CREATE OR REPLACE FUNCTION datetime(spec text) RETURNS text
  LANGUAGE plpgsql STABLE AS $fn$
BEGIN
  IF spec <> 'now' THEN
    RAISE EXCEPTION 'datetime(%) is not implemented by the scim-bridge Postgres driver; only datetime(''now'')', spec;
  END IF;
  RETURN to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');
END
$fn$;

CREATE TABLE IF NOT EXISTS app_state (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS poc_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

-- Non-secret defaults, as in migration 0002/0003/0004. The bundled endpoints'
-- bearer tokens are deliberately NOT here: the app mints them at boot, so their
-- value cannot depend on which datastore you chose (workers/shared/ids.ts).
INSERT INTO poc_config (key, value) VALUES ('native.webhook_secret', '') ON CONFLICT (key) DO NOTHING;
INSERT INTO poc_config (key, value) VALUES ('proxy.public_url', 'http://localhost:8787') ON CONFLICT (key) DO NOTHING;
INSERT INTO poc_config (key, value) VALUES ('native.public_url', 'http://localhost:8788') ON CONFLICT (key) DO NOTHING;
INSERT INTO poc_config (key, value) VALUES ('idp.public_url', 'http://localhost:8789') ON CONFLICT (key) DO NOTHING;
INSERT INTO poc_config (key, value) VALUES ('mock_workos.emit_dsync', 'true') ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS scim_directories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'passthrough'
    CHECK (mode IN ('passthrough', 'dual-write', 'workos-only')),
  proxy_token TEXT NOT NULL UNIQUE,
  native_url TEXT NOT NULL DEFAULT '',
  native_token TEXT NOT NULL DEFAULT '',
  workos_url TEXT NOT NULL DEFAULT '',
  workos_token TEXT NOT NULL DEFAULT '',
  workos_directory_id TEXT,
  log_persistence INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_scim_directories_workos_directory_id
  ON scim_directories (workos_directory_id)
  WHERE workos_directory_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS id_mappings (
  directory_id TEXT NOT NULL,
  resource_type TEXT NOT NULL CHECK (resource_type IN ('Users', 'Groups')),
  native_id TEXT NOT NULL,
  workos_id TEXT NOT NULL,
  strategy TEXT NOT NULL CHECK (strategy IN ('migrated-id', 'fallback-post')),
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now'),
  PRIMARY KEY (directory_id, resource_type, native_id)
);

CREATE INDEX IF NOT EXISTS idx_id_mappings_workos
  ON id_mappings (directory_id, resource_type, workos_id);

-- SQLite's INTEGER PRIMARY KEY AUTOINCREMENT. Nothing reads the generated value
-- back (the Datastore contract has no last_row_id), so an identity column is a
-- straight swap.
CREATE TABLE IF NOT EXISTS proxy_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  directory_id TEXT,
  ts TEXT NOT NULL DEFAULT datetime('now'),
  source TEXT NOT NULL DEFAULT 'idp' CHECK (source IN ('idp', 'backfill')),
  mode TEXT NOT NULL,
  method TEXT NOT NULL,
  path TEXT NOT NULL,
  request_body TEXT,
  native_status INTEGER,
  native_ms INTEGER,
  native_body TEXT,
  workos_request TEXT,
  workos_status INTEGER,
  workos_ms INTEGER,
  workos_body TEXT,
  response_status INTEGER,
  error TEXT
);

CREATE INDEX IF NOT EXISTS idx_proxy_log_directory ON proxy_log (directory_id, id DESC);

CREATE TABLE IF NOT EXISTS native_users (
  id TEXT PRIMARY KEY,
  user_name TEXT NOT NULL UNIQUE,
  external_id TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  resource TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS native_groups (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  external_id TEXT,
  resource TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS native_group_members (
  group_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS mock_workos_users (
  id TEXT PRIMARY KEY,
  user_name TEXT NOT NULL UNIQUE,
  external_id TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  resource TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS mock_workos_groups (
  id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  external_id TEXT,
  resource TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE TABLE IF NOT EXISTS mock_workos_group_members (
  group_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS listener_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TEXT NOT NULL DEFAULT datetime('now'),
  event_id TEXT,
  event_type TEXT NOT NULL,
  idp_id TEXT,
  action TEXT NOT NULL CHECK (action IN ('applied', 'skipped', 'ignored')),
  detail TEXT,
  payload TEXT
);

CREATE TABLE IF NOT EXISTS listener_versions (
  scope TEXT PRIMARY KEY,
  event_at TEXT NOT NULL
);

-- The bundled IdP simulator (DEMO_MODE only), kept in the baseline so the two
-- schemas stay comparable table for table.
CREATE TABLE IF NOT EXISTS idp_users (
  id TEXT PRIMARY KEY,
  directory_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  external_id TEXT NOT NULL,
  given_name TEXT,
  family_name TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  scim_id TEXT,
  last_status INTEGER,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_idp_users_conn_username
  ON idp_users (directory_id, user_name);

CREATE TABLE IF NOT EXISTS idp_groups (
  id TEXT PRIMARY KEY,
  directory_id TEXT NOT NULL,
  display_name TEXT NOT NULL,
  external_id TEXT NOT NULL,
  scim_id TEXT,
  last_status INTEGER,
  created_at TEXT NOT NULL DEFAULT datetime('now'),
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_idp_groups_conn_name
  ON idp_groups (directory_id, display_name);

CREATE TABLE IF NOT EXISTS idp_group_members (
  group_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS idp_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  directory_id TEXT NOT NULL,
  ts TEXT NOT NULL DEFAULT datetime('now'),
  origin TEXT NOT NULL DEFAULT 'manual' CHECK (origin IN ('manual', 'auto', 'seed')),
  action TEXT NOT NULL,
  subject TEXT,
  method TEXT,
  path TEXT,
  status INTEGER,
  ok INTEGER NOT NULL DEFAULT 1,
  detail TEXT
);

CREATE INDEX IF NOT EXISTS idx_idp_activity_conn ON idp_activity (directory_id, id DESC);

CREATE TABLE IF NOT EXISTS idp_auto_state (
  directory_id TEXT PRIMARY KEY,
  running INTEGER NOT NULL DEFAULT 0,
  interval_ms INTEGER NOT NULL DEFAULT 4000,
  tick_count INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT datetime('now')
);
