-- Postgres side of migrations/0012_mock_workos_events.sql: the ordered event
-- log behind the mock WorkOS GET /events endpoint.
CREATE TABLE IF NOT EXISTS mock_workos_events (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id TEXT NOT NULL UNIQUE,
  event TEXT NOT NULL,
  data TEXT NOT NULL,
  created_at TEXT NOT NULL
);
